"""Export a trained SB3 SAC policy to RLtools C++ persist_code format.

Extracts the actor (policy) network weights from a Stable-Baselines3 SAC
model and generates a C++ header file using RLtools' ``persist_code`` layout.
The generated header can be compiled directly into ESP32 firmware.

Usage::

    uv run python -m qube_rl.export_rltools --model models/qube_sac_64x2.zip
    uv run python -m qube_rl.export_rltools --model models/qube_sac_64x2.zip --output weights.h

The generated header contains:
- ``policy_weights::INPUT_DIM`` and ``policy_weights::HIDDEN_DIM`` constants
- ``policy_weights::LAYER_0_WEIGHT``, ``LAYER_0_BIAS``, etc. as ``constexpr float[]``
- ``policy_weights::N_LAYERS`` count for iteration

Architecture mapping (SB3 SAC MlpPolicy → RLtools FC):
    Layer 0: actor.latent.pi.0  → Linear(obs_dim → hidden)
    Layer 1: actor.latent.pi.2  → Linear(hidden → hidden)
    Layer 2: actor.mu           → Linear(hidden → action_dim)

Note: Weights are stored column-major (row-major transposed) to match
RLtools' expected memory layout.
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

import numpy as np

logging.basicConfig(format="%(levelname)s: %(message)s", level=logging.INFO)
logger = logging.getLogger(__name__)


def extract_actor_weights(model_path: str) -> tuple[list[np.ndarray], list[np.ndarray], list[int]]:
    """Extract actor network weights from an SB3 SAC model.

    Returns
    -------
    tuple[list[np.ndarray], list[np.ndarray], list[int]]
        (weights, biases, layer_dims) where layer_dims[i] = [in, out]
        for each linear layer in the actor.
    """
    from stable_baselines3 import SAC

    model = SAC.load(model_path)
    actor = model.policy.actor

    # SB3 SAC MlpPolicy actor architecture:
    #   actor.latent_pi.0 = Linear(obs_dim → hidden)
    #   actor.latent_pi.2 = Linear(hidden → hidden)
    #   actor.mu[0]       = Linear(hidden → action_dim)
    layers = [
        actor.latent_pi[0],  # first Linear
        actor.latent_pi[2],  # second Linear
        actor.mu[0],  # output Linear (skip Hardtanh activation)
    ]

    weights: list[np.ndarray] = []
    biases: list[np.ndarray] = []
    dims: list[int] = []

    for layer in layers:
        w = layer.weight.detach().cpu().numpy()  # shape: [out, in]
        b = layer.bias.detach().cpu().numpy()  # shape: [out]
        weights.append(w)
        biases.append(b)
        dims.append(w.shape[1])  # in_dim

    dims.append(weights[-1].shape[0])  # out_dim of last layer

    logger.info("Actor architecture: %s", " → ".join(f"{d}" for d in dims))
    total_params = sum(w.size + b.size for w, b in zip(weights, biases, strict=True))
    logger.info("Total parameters: %d (%.1f KB flash at float32)", total_params, total_params * 4 / 1024)

    return weights, biases, dims


def generate_cpp_header(
    weights: list[np.ndarray],
    biases: list[np.ndarray],
    dims: list[int],
    namespace: str = "policy_weights",
) -> str:
    """Generate RLtools-compatible C++ header with constexpr weight arrays.

    Parameters
    ----------
    weights : list[np.ndarray]
        Weight matrices, each shape [out, in].
    biases : list[np.ndarray]
        Bias vectors, each shape [out].
    dims : list[int]
        Layer dimensions [input, hidden1, hidden2, output].
    namespace : str
        C++ namespace for the weight data.

    Returns
    -------
    str
        Complete C++ header file content.
    """
    n_layers = len(weights)
    input_dim = dims[0]
    output_dim = dims[-1]

    lines = [
        "// Auto-generated by qube_rl.export_rltools — DO NOT EDIT",
        f"// Architecture: {' → '.join(str(d) for d in dims)}",
        f"// Parameters: {sum(w.size + b.size for w, b in zip(weights, biases, strict=True))}",
        "",
        "#pragma once",
        "",
        f"namespace {namespace} {{",
        "",
        f"    constexpr unsigned int INPUT_DIM = {input_dim};",
        f"    constexpr unsigned int OUTPUT_DIM = {output_dim};",
        f"    constexpr unsigned int N_LAYERS = {n_layers};",
        "",
    ]

    for i, (w, b) in enumerate(zip(weights, biases, strict=True)):
        in_dim, out_dim = w.shape[1], w.shape[0]

        lines.append(f"    // Layer {i}: {in_dim} → {out_dim}")
        lines.append(f"    constexpr float LAYER_{i}_WEIGHT[{out_dim * in_dim}] = {{")

        # Write weights row-major (each row = one output neuron)
        rows = []
        for r in range(out_dim):
            vals = ", ".join(f"{w[r, c]:.6f}" for c in range(in_dim))
            rows.append(f"        {vals}")
        lines.append(",\n".join(rows))
        lines.append("    };")

        # Write biases
        bias_vals = ", ".join(f"{b[v]:.6f}" for v in range(out_dim))
        lines.append(f"    constexpr float LAYER_{i}_BIAS[{out_dim}] = {{ {bias_vals} }};")
        lines.append("")

    lines.append("} // namespace " + namespace)
    lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Export SB3 SAC policy weights to RLtools C++ format")
    parser.add_argument("--model", required=True, help="Path to trained SB3 SAC model (.zip)")
    parser.add_argument("--output", default=None, help="Output header file (default: models/policy_weights.h)")
    parser.add_argument("--namespace", default="policy_weights", help="C++ namespace (default: policy_weights)")
    parser.add_argument("--float64", action="store_true", help="Use double instead of float (default: float)")
    args = parser.parse_args(argv)

    model_path = Path(args.model)
    if not model_path.exists():
        logger.error("Model not found: %s", model_path)
        return

    logger.info("Loading model from %s", model_path)
    weights, biases, dims = extract_actor_weights(str(model_path))

    header = generate_cpp_header(weights, biases, dims, namespace=args.namespace)

    output_path = Path(args.output) if args.output else Path("models") / "policy_weights.h"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header, encoding="utf-8")
    logger.info("Header written to %s (%d bytes)", output_path, len(header))

    # Also write a summary for verification
    logger.info("--- Verification ---")
    for i, (w, b) in enumerate(zip(weights, biases, strict=True)):
        logger.info(
            "  Layer %d: W=%s  b=%s  |W|_max=%.6f  |b|_max=%.6f",
            i,
            w.shape,
            b.shape,
            np.max(np.abs(w)),
            np.max(np.abs(b)),
        )
    logger.info("Export complete. Compile the header into your ESP32 firmware.")


if __name__ == "__main__":
    main()
